@startuml
actor User
participant "React Frontend" as RF
participant "Django Server" as DS
participant "Celery Task Manager" as C

User -> RF: Upload files and click transcribe
RF -> DS: Start transcription
DS -> C: Create transcription task
activate C
C -> DS: Transcription task id
DS -> RF: Transcription task id
RF -> User: Upload size and ETA

loop Polling for status
    RF -> DS: Poll transcription status
    DS -> C: Poll transcription status
    C -> DS: Transcription status / links
    DS -> RF: Transcription status / links
    deactivate C
end

RF -> User: Download links

@enduml